name: Build solution

on:
  push:
    branches:
    - main
    - docs-and-ci
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Smartersoft.Identity.Client.Assertion.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: '5.x'

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    
    - name: Run formatter
      run: dotnet format $SOLUTION --no-restore
