name: Release az-kv-proxy

on:
  push:
    branches:
    - main
    paths:
      - .github/workflows/release-proxy.yml
      - src/Smartersoft.Identity.Client.Assertion/**/*.cs
      - src/Smartersoft.Identity.Client.Assertion.Proxy/**/*.cs
      - src/Smartersoft.Identity.Client.Assertion.Proxy/*.csproj
    
jobs:
  build-and-push:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Smartersoft.Identity.Client.Assertion.sln'
      PROJECT: 'src/Smartersoft.Identity.Client.Assertion.Proxy/Smartersoft.Identity.Client.Assertion.Proxy.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
        additionalArguments: /updateprojectfiles

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build solution
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    
    - name: Create nuget package
      run: dotnet pack $PROJECT -c $BUILD_CONFIG --no-build --no-restore --output .

    - name: Push KeyVault proxy to NuGet
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
